apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-dashboard
  namespace: mff
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: status-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"

    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  tls:
  - hosts:
    - status.mff-server.com
    secretName: status-mff-server-tls
  rules:
  - host: status.mff-server.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft-dashboard
            port:
              number: 80
